### Task 1: Creating NumPy Arrays
1. Import NumPy as np.
2. Create the following arrays:
- A 1D array of integers from 1 to 10
- A 2D array of shape (3, 3) with values from 1 to 9
- A NumPy array from the list: [10, 20, 30, 40, 50]
3. Print:
- Shape of each array
- Data type of each array

In [2]:
import numpy as np
import logging
import sys

# Configuring the logging module ->as usual using basicConfig with a StreamHandler directed to sys.stdout.
logging.basicConfig(
    level=logging.INFO,
    format='%(message)s',
    handlers=[logging.StreamHandler(sys.stdout)]
)
logger = logging.getLogger(__name__)

def create_arrays():
    
    # Task 1: Creating NumPy Arrays
    
    # 1D array -> a vector for sequential data store.-> np.arange(1, 11) used (1 included and 11 excluded).
    array_1d = np.arange(1, 11)
    # Logging shape and data type.->verifies no of elements (.shape)and (.dtype)
    logger.info(f"1D Array Shape: {array_1d.shape}")
    logger.info(f"1D Array Data Type: {array_1d.dtype}")

    # 2D array of shape (3, 3) -> matrix construction -> 9 elements arange(1, 10) and applying.reshape(3, 3) method.
    array_2d = np.arange(1, 10).reshape(3, 3)
    # similiar to previous -> confirms the 3x3 dimensionality and integer representation.
    logger.info(f"2D Array Shape: {array_2d.shape}")
    logger.info(f"2D Array Data Type: {array_2d.dtype}")

    # NumPy array -> standard Python data structures into NumPy arrays for vector applications
    list_input = [10, 20, 30, 40, 50]
    array_from_list = np.array(list_input)
    
    # ensure conversion preserved 5-element length and identified the data as integers.
    logger.info(f"List-derived Array Shape: {array_from_list.shape}")
    logger.info(f"List-derived Array Data Type: {array_from_list.dtype}")

create_arrays()


1D Array Shape: (10,)
1D Array Data Type: int64
2D Array Shape: (3, 3)
2D Array Data Type: int64
List-derived Array Shape: (5,)
List-derived Array Data Type: int64


### Task 2: Important Mathematical Operations
- Given two arrays:
A = np.array([10, 20, 30, 40])
B = np.array([1, 2, 3,4])
- Perform and print results for:

1. Addition (A + B)
2. Subtraction (A - B)
3. Multiplication (A * B)
4. Division (A / B)
5. Power (A ** 2)
6. Extra (optional): Use NumPy functions: np.add(), np.subtract() for the same operations.


In [3]:
def mathematical_Operations():

    # Task 2: applying mathematical operations

    A = np.array([10, 20, 30, 40])
    B = np.array([1, 2, 3, 4])

    logger.info(f"Array A: {A}")
    logger.info(f"Array B: {B}\n")

    # Performing element-wise addition (A + B). without using loops. -> Using '+' operator and np.add(A, B).
    add_op = A + B
    add_func = np.add(A, B)
    logger.info(f"1. Addition (A + B): {add_op}")
    logger.info(f"   (Using np.add):   {add_func}")

    # Performing element-wise subtraction (A - B). lly as add
    sub_op = A - B
    sub_func = np.subtract(A, B)
    logger.info(f"2. Subtraction (A - B): {sub_op}")
    logger.info(f"   (Using np.subtract): {sub_func}")

    # Performing element-wise multiplication (A * B). lly as previous
    mul_op = A * B
    mul_func = np.multiply(A, B)
    logger.info(f"3. Multiplication (A * B): {mul_op}")
    logger.info(f"   (Using np.multiply):      {mul_func}")

    # Performing element-wise division (A / B). NumPy handles this via float conversion by default.
    div_op = A / B
    div_func = np.divide(A, B)
    logger.info(f"4. Division (A / B): {div_op}")
    logger.info(f"   (Using np.divide):   {div_func}")

    # Performing element-wise power/exponentiation (A ** 2).
    pow_op = A ** 2
    pow_func = np.power(A, 2)
    logger.info(f"5. Power (A ** 2): {pow_op}")
    logger.info(f"   (Using np.power):  {pow_func}")

mathematical_Operations()

Array A: [10 20 30 40]
Array B: [1 2 3 4]

1. Addition (A + B): [11 22 33 44]
   (Using np.add):   [11 22 33 44]
2. Subtraction (A - B): [ 9 18 27 36]
   (Using np.subtract): [ 9 18 27 36]
3. Multiplication (A * B): [ 10  40  90 160]
   (Using np.multiply):      [ 10  40  90 160]
4. Division (A / B): [10. 10. 10. 10.]
   (Using np.divide):   [10. 10. 10. 10.]
5. Power (A ** 2): [ 100  400  900 1600]
   (Using np.power):  [ 100  400  900 1600]


### Task 3: Important NumPy Mathematical Formulas
- Given:
values = np.array([2, 4, 6, 8, 10])
- Calculate:
1. Square root of each element
2. Exponential of each element
3. Natural logarithm of each element
4. Sum of all elements
5. Cumulative sum of elements Use NumPy functions only.

In [4]:
def numpy_Formulas():
    # Task 3: NumPy mathematical formulas and aggregations.
    
    #intializing array 
    values = np.array([2, 4, 6, 8, 10])
    logger.info(f"Input Values: {values}\n")

    # Calculating square root of each element.-> vectorized np.sqrt() function.
    sqrt_vals = np.sqrt(values)
    logger.info(f"1. Square Root: {sqrt_vals}")

    # What: Calculating exponential (e^x) of each element. -> Applying np.exp() function.
    exp_vals = np.exp(values)
    logger.info(f"2. Exponential (e^x): {exp_vals}")

    # Calculating natural logarithm (ln) of each element.-> Applying np.log() function.
    log_vals = np.log(values)
    logger.info(f"3. Natural Logarithm: {log_vals}")

    # Calculating the sum of all elements in the array.-> Applying the np.sum() reduction function.
    total_sum = np.sum(values)
    logger.info(f"4. Sum of elements: {total_sum}")

    # Calculating the cumulative sum (running total).-> Applying np.cumsum(), which returns array of same shape as 'values'.
    cumulative_sum = np.cumsum(values)
    logger.info(f"5. Cumulative Sum: {cumulative_sum}")

# Executing Task 3
numpy_Formulas()

Input Values: [ 2  4  6  8 10]

1. Square Root: [1.41421356 2.         2.44948974 2.82842712 3.16227766]
2. Exponential (e^x): [7.38905610e+00 5.45981500e+01 4.03428793e+02 2.98095799e+03
 2.20264658e+04]
3. Natural Logarithm: [0.69314718 1.38629436 1.79175947 2.07944154 2.30258509]
4. Sum of elements: 30
5. Cumulative Sum: [ 2  6 12 20 30]


### Task 4: Aggregation Operations
- Given a 2D array:
data = np.array([
[10, 20, 30],
[40, 50, 60],
[70, 80,90]
])
- Find:
1. Row-wise sum
2. Column-wise sum
3. Minimum value
4. Maximum value
5. Overall mean


In [5]:
def task_4_aggregation_operations():
    # Task 4: Performing multi-axis aggregation on 2D NumPy array.
    
    # Initializing a 3x3 2D array 
    data = np.array([
        [10, 20, 30],
        [40, 50, 60],
        [70, 80, 90]
    ])
    logger.info(f"Input Matrix:\n{data}\n")

    # Calculating the row-wise sum.-> Using np.sum() with axis=1 to collapse the horizontal dimension.
    row_sum = np.sum(data, axis=1)
    logger.info(f"1. Row-wise Sum (Axis 1): {row_sum}")

    # Calculating the column-wise sum.-> Using np.sum() with axis=0 to collapse the vertical dimension.
    col_sum = np.sum(data, axis=0)
    logger.info(f"2. Column-wise Sum (Axis 0): {col_sum}")

    # Finding min -> Applying the global np.min() function without specifying an axis (array 2D -> flatten array).
    min_val = np.min(data)
    logger.info(f"3. Minimum Value: {min_val}")

    #Finding maxi value. -> Applying the global np.max().
    max_val = np.max(data)
    logger.info(f"4. Maximum Value: {max_val}")

    # mean. -> determines central tendency of matrix. -> Using np.mean() compute average of all elements.
    overall_mean = np.mean(data)
    logger.info(f"5. Overall Mean: {overall_mean}")

# Executing Task 4
task_4_aggregation_operations()


Input Matrix:
[[10 20 30]
 [40 50 60]
 [70 80 90]]

1. Row-wise Sum (Axis 1): [ 60 150 240]
2. Column-wise Sum (Axis 0): [120 150 180]
3. Minimum Value: 10
4. Maximum Value: 90
5. Overall Mean: 50.0


### Task 5: Statistical Operations (Core Focus)
- Given:
marks = np.array([78, 85, 90, 66, 72, 88, 95, 60])
- Calculate and print:
1. Mean
2. Median
3. Variance
4. Standard Deviation
5. Minimum & Maximum
6. Range (max - min)


In [6]:
def statistical_Operations():
    # Task 5: Statistical analysis using NumPy.
    
    # Initializing 'marks' array.
    marks = np.array([78, 85, 90, 66, 72, 88, 95, 60])
    logger.info(f"Dataset (Marks): {marks}\n")

    # Calculating the Mean. -> find average performance -> Using np.mean(marks).
    mean_val = np.mean(marks)
    logger.info(f"1. Mean: {mean_val}")

    # Calculating the Median. -> find central value -> Using np.median(marks).
    median_val = np.median(marks)
    logger.info(f"2. Median: {median_val}")

    # Calculating the Variance.-> To quantify spread of marks around mean -> Using np.var(marks).
    variance_val = np.var(marks)
    logger.info(f"3. Variance: {variance_val:.2f}")

    # Calculating the Standard Deviation. -> To understand average distance of marks from mean. ->Using np.std(marks).
    std_dev = np.std(marks)
    logger.info(f"4. Standard Deviation: {std_dev:.2f}")


    min_mark = np.min(marks)
    max_mark = np.max(marks)
    logger.info(f"5. Minimum: {min_mark}, Maximum: {max_mark}")

    # Calculating the Range. determine total spread between highest and lowest scores. -> Subtracting np.min() from np.max().
    mark_range = max_mark - min_mark
    logger.info(f"6. Range: {mark_range}")

# Executing Task 5
statistical_Operations()

Dataset (Marks): [78 85 90 66 72 88 95 60]

1. Mean: 79.25
2. Median: 81.5
3. Variance: 134.19
4. Standard Deviation: 11.58
5. Minimum: 60, Maximum: 95
6. Range: 35


### Task 6: Percentiles & Sorting
- Using the same marks array:
Sort the array
- Find:
1. 25th percentile
2. 50th percentile
3. 75th percentile
4. Count how many students scored above the average marks


In [7]:
def percentiles_And_Sorting():
    """
    Task 6: sorting and percentiles.
    """
    
    # Re-initializing the 'marks' array from Task 5.
    marks = np.array([78, 85, 90, 66, 72, 88, 95, 60])
    logger.info(f"Original Marks: {marks}")

    # Sorting in ascending order. -> Using np.sort(marks), which returns sorted copy of array.
    sorted_marks = np.sort(marks)
    logger.info(f"1. Sorted Marks: {sorted_marks}")

    # Finding the 25th, 50th, and 75th percentiles.
    # Applying np.percentile()
    p25, p50, p75 = np.percentile(marks, [25, 50, 75])
    logger.info(f"2. Percentiles:")
    logger.info(f"\n - 25th Percentile (Q1): {p25}")
    logger.info(f"\n - 50th Percentile (Median/Q2): {p50}")
    logger.info(f"\n - 75th Percentile (Q3): {p75}")

    # Counting students who scored above  average marks.
    avg_marks = np.mean(marks)
    above_avg_count = np.sum(marks > avg_marks)
    
    logger.info(f"\nAverage Marks: {avg_marks}")
    logger.info(f"3. Students scoring above average: {above_avg_count}")

# Executing Task 6
percentiles_And_Sorting()


Original Marks: [78 85 90 66 72 88 95 60]
1. Sorted Marks: [60 66 72 78 85 88 90 95]
2. Percentiles:

 - 25th Percentile (Q1): 70.5

 - 50th Percentile (Median/Q2): 81.5

 - 75th Percentile (Q3): 88.5

Average Marks: 79.25
3. Students scoring above average: 4


### Task 7: Mini Use Case: Sales Analysis
- Given daily sales data:
sales = np.array([1200, 1500, 900, 2000, 1800, 1700, 1600])
- Perform:
1. Total weekly sales
2. Average daily sales
3. Highest and lowest sales day
3. Standard deviation of sales
4. Identify days where sales were above average


In [8]:

def sales_Analysis():
    """
    Task 7: Mini Use Case - Sales Analysis for a 7-day period.
    """
    
    # Initializing 'sales' array 
    sales = np.array([1200, 1500, 900, 2000, 1800, 1700, 1600])
    logger.info(f"Daily Sales Data: {sales}\n")

    # Calculating total weekly sales.-> determine total revenue generated 
    total_sales = np.sum(sales)
    logger.info(f"1. Total Weekly Sales: INR {total_sales}")

    # Calculating average daily sales -> To establish a performance benchmark.
    avg_sales = np.mean(sales)
    logger.info(f"2. Average Daily Sales: INR {avg_sales:.2f}")

    # Finding the highest and lowest sales values. -> To identify peak performance day and biggest slump
    max_sales = np.max(sales)
    min_sales = np.min(sales)
    logger.info(f"3. Highest Sales Day: INR {max_sales}")
    logger.info(f"   Lowest Sales Day:  INR {min_sales}")

    # Calculating Standard Deviation of sales. -> To measure consistency and stability of daily revenue.
    sales_std = np.std(sales)
    logger.info(f"4. Standard Deviation of Sales: INR {sales_std:.2f}")

    # Identifying days where sales were above average. -> To pinpoint high-performance windows for further business strategy.
    above_avg_sales = sales[sales > avg_sales]
    logger.info(f"5. Sales values above average: {above_avg_sales}")

# Executing Task 7
sales_Analysis()


Daily Sales Data: [1200 1500  900 2000 1800 1700 1600]

1. Total Weekly Sales: INR 10700
2. Average Daily Sales: INR 1528.57
3. Highest Sales Day: INR 2000
   Lowest Sales Day:  INR 900
4. Standard Deviation of Sales: INR 345.23
5. Sales values above average: [2000 1800 1700 1600]
